# Copyright (c) Microsoft. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "azure-iot-sdk"
BBFILE_PATTERN_azure-iot-sdk = "^${LAYERDIR}/"
BBFILE_PRIORITY_azure-iot-sdk = "6"

LAYERVERSION_azure-iot-sdk = "1"
LAYERDEPENDS_azure-iot-sdk = "core"
LAYERSERIES_COMPAT_azure-iot-sdk = "scarthgap"
