name: Deploy faultable MQTT broker
description: Copy faultable MQTT broker from AIO SDK repo, build it, and run it on port 1884 for local fault injection testing

runs:
  using: composite
  steps:
    - name: Copy Faultable MQTT broker from AIO SDK repo
      uses: azure/powershell@v3
      with:
        azPSVersion: "latest"
        inlineScript: |
          mkdir faultablemqttbroker
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Azure/iot-operations-sdks/refs/heads/main/eng/test/faultablemqttbroker/src/Azure.Iot.Operations.FaultableMqttBroker/Azure.Iot.Operations.FaultableMqttBroker.csproj" -OutFile "./faultablemqttbroker/Azure.Iot.Operations.FaultableMqttBroker.csproj"
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Azure/iot-operations-sdks/refs/heads/main/eng/test/faultablemqttbroker/src/Azure.Iot.Operations.FaultableMqttBroker/FaultHandling.cs" -OutFile "./faultablemqttbroker/FaultHandling.cs"
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Azure/iot-operations-sdks/refs/heads/main/eng/test/faultablemqttbroker/src/Azure.Iot.Operations.FaultableMqttBroker/FaultableMqttBroker.cs" -OutFile "./faultablemqttbroker/FaultableMqttBroker.cs"
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Azure/iot-operations-sdks/refs/heads/main/eng/test/faultablemqttbroker/src/Azure.Iot.Operations.FaultableMqttBroker/FaultableMqttBrokerWorker.cs" -OutFile "./faultablemqttbroker/FaultableMqttBrokerWorker.cs"
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Azure/iot-operations-sdks/refs/heads/main/eng/test/faultablemqttbroker/src/Azure.Iot.Operations.FaultableMqttBroker/Program.cs" -OutFile "./faultablemqttbroker/Program.cs"

    - name: Build Faultable MQTT Broker
      uses: azure/powershell@v3
      with:
        azPSVersion: "latest"
        inlineScript: |
          dotnet build ./faultablemqttbroker/Azure.Iot.Operations.FaultableMqttBroker.csproj
   
    - name: Run Faultable MQTT Broker (port 1884)
      uses: azure/powershell@v3
      with:
        azPSVersion: "latest"
        inlineScript: |
          $WorkingDirectory = pwd
          $job = Start-Job -ScriptBlock { dotnet run --project ".\faultablemqttbroker\Azure.Iot.Operations.FaultableMqttBroker.csproj" } -WorkingDirectory $WorkingDirectory
          
          # Check that the job is running correctly
          Start-Sleep -Seconds 3
          if ($job.State -ne "Running")
          {
            Write-Output "Faultable MQTT broker did not start up correctly:"
            $job
            exit 1
          }
