#Requires -Version 7.2
<#
.SYNOPSIS
    Builds the SDK and prepares environment variables to run samples against the mock broker.

.DESCRIPTION
    1. Configures CMake (samples ON, tests ON).
    2. Builds the telemetry sample.
    3. Writes a .env.ps1 file that can be dot-sourced to set all required env vars.
    4. Validates connectivity to the mock broker (quick mosquitto_pub via docker exec).

.PARAMETER DeviceId
    Device identity. Must match the cert CN generated by New-TestEnv.ps1.
    Default: "test-device-01"

.PARAMETER BrokerPort
    Host port of the mock broker. Default: 8883

.PARAMETER BuildPreset
    CMake preset name. If empty, raw cmake configure is used.

.EXAMPLE
    .\New-TestClient.ps1
    . .\.client-env.ps1
    .\..\..\build\samples\gen2\Debug\az_iot_sample_telemetry.exe
#>
[CmdletBinding()]
param(
    [string]$DeviceId = "test-device-01",
    [int]$BrokerPort = 8883,
    [string]$BuildPreset = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$ScriptDir   = $PSScriptRoot
$RepoRoot    = (Resolve-Path (Join-Path $ScriptDir "..\..")).Path
$BuildDir    = Join-Path $RepoRoot "build"
$CertsDir    = Join-Path $ScriptDir ".certs"
$EnvFile     = Join-Path $ScriptDir ".client-env.ps1"

# ─────────────────────────────────────────────────────────────────────────────
# Validate environment
# ─────────────────────────────────────────────────────────────────────────────

Write-Host "=== Build & Configure Test Client ===" -ForegroundColor Cyan

if (-not (Test-Path (Join-Path $CertsDir "ca.crt"))) {
    throw "Certificates not found in $CertsDir. Run .\New-TestEnv.ps1 first."
}

$deviceCert = Join-Path $CertsDir "$DeviceId.crt"
$deviceKey  = Join-Path $CertsDir "$DeviceId.key"
$caCert     = Join-Path $CertsDir "ca.crt"

if (-not (Test-Path $deviceCert)) {
    throw "Device cert not found: $deviceCert. Re-run New-TestEnv.ps1 with -DeviceId $DeviceId."
}

# ─────────────────────────────────────────────────────────────────────────────
# CMake configure + build
# ─────────────────────────────────────────────────────────────────────────────

Write-Host "[build] Configuring CMake..."
if ($BuildPreset) {
    cmake --preset $BuildPreset -S $RepoRoot -B $BuildDir
} else {
    cmake -S $RepoRoot -B $BuildDir -DAZ_IOT_BUILD_SAMPLES=ON -DAZ_IOT_BUILD_TESTS=ON
}
if ($LASTEXITCODE -ne 0) { throw "CMake configure failed." }

Write-Host "[build] Building telemetry sample..."
cmake --build $BuildDir --config Debug --target az_iot_sample_gen2_telemetry
if ($LASTEXITCODE -ne 0) { throw "Build failed." }

$TelemetrySampleExe = Join-Path $BuildDir "samples\gen2\Debug\az_iot_sample_telemetry.exe"
if (-not (Test-Path $TelemetrySampleExe)) {
    # Try non-multi-config generator path
    $TelemetrySampleExe = Join-Path $BuildDir "samples\gen2\az_iot_sample_telemetry.exe"
}

Write-Host "[build] Building direct methods sample..."
cmake --build $BuildDir --config Debug --target az_iot_sample_gen2_direct_method_responder
if ($LASTEXITCODE -ne 0) { throw "Build failed." }

$DirectMethodSampleExe = Join-Path $BuildDir "samples\gen2\Debug\az_iot_sample_direct_method_responder.exe"
if (-not (Test-Path $DirectMethodSampleExe)) {
    # Try non-multi-config generator path
    $DirectMethodSampleExe = Join-Path $BuildDir "samples\gen2\az_iot_sample_direct_method_responder.exe"
}

Write-Host "[build] Building twin sample..."
cmake --build $BuildDir --config Debug --target az_iot_sample_gen2_twin_get_patch
if ($LASTEXITCODE -ne 0) { throw "Build failed." }

$TwinSampleExe = Join-Path $BuildDir "samples\gen2\Debug\az_iot_sample_twin_get_patch.exe"
if (-not (Test-Path $TwinSampleExe)) {
    # Try non-multi-config generator path
    $TwinSampleExe = Join-Path $BuildDir "samples\gen2\az_iot_sample_twin_get_patch.exe"
}

Write-Host "[build] Building C2D receiver sample..."
cmake --build $BuildDir --config Debug --target az_iot_sample_gen2_c2d_receiver
if ($LASTEXITCODE -ne 0) { throw "Build failed." }

$C2dSampleExe = Join-Path $BuildDir "samples\gen2\Debug\az_iot_sample_c2d_receiver.exe"
if (-not (Test-Path $C2dSampleExe)) {
    # Try non-multi-config generator path
    $C2dSampleExe = Join-Path $BuildDir "samples\gen2\az_iot_sample_c2d_receiver.exe"
}

# ─────────────────────────────────────────────────────────────────────────────
# Generate .env file
# ─────────────────────────────────────────────────────────────────────────────

Write-Host "[env] Writing: $EnvFile"

$envContent = @"
# Auto-generated by New-TestClient.ps1 — dot-source this before running the sample.
# Usage: . '$EnvFile'

`$env:AZ_IOT_HUB_NEXT_MOCK_ENDPOINT = "localhost:$BrokerPort"
`$env:AZ_IOT_DEVICE_ID              = "$DeviceId"
`$env:AZ_IOT_CLIENT_CERT            = "$($deviceCert -replace '\\','\\')"
`$env:AZ_IOT_CLIENT_KEY             = "$($deviceKey -replace '\\','\\')"
`$env:AZ_IOT_TRUSTED_CA             = "$($caCert -replace '\\','\\')"
`$env:AZ_IOT_DPS_ID_SCOPE           = "0ne00000000"
`$env:AZ_IOT_DPS_REGISTRATION_ID    = "$DeviceId"

Write-Host "Environment configured for device: $DeviceId -> localhost:$BrokerPort" -ForegroundColor Green
"@

Set-Content -Path $EnvFile -Value $envContent -NoNewline

# ─────────────────────────────────────────────────────────────────────────────
# Quick connectivity check
# ─────────────────────────────────────────────────────────────────────────────

Write-Host "[test] Verifying broker reachability on localhost:$BrokerPort..."
$tcpTest = Test-NetConnection -ComputerName "localhost" -Port $BrokerPort -WarningAction SilentlyContinue
if ($tcpTest.TcpTestSucceeded) {
    Write-Host "[test] Broker is reachable." -ForegroundColor Green
} else {
    Write-Warning "Cannot reach localhost:$BrokerPort. Is the mock environment running? (.\New-TestEnv.ps1)"
}

# ─────────────────────────────────────────────────────────────────────────────
# Done
# ─────────────────────────────────────────────────────────────────────────────

Write-Host ""
Write-Host "Client ready." -ForegroundColor Green
Write-Host ""
Write-Host "  To run the telemetry sample:" -ForegroundColor White
Write-Host "    . '$EnvFile'"
Write-Host "    & '$TelemetrySampleExe'"
Write-Host ""
Write-Host "  To run the direct methods sample:" -ForegroundColor White
Write-Host "    . '$EnvFile'"
Write-Host "    & '$DirectMethodSampleExe'"
Write-Host ""
Write-Host "  To run the twin sample:" -ForegroundColor White
Write-Host "    . '$EnvFile'"
Write-Host "    & '$TwinSampleExe'"
Write-Host ""
Write-Host "  To run the C2D receiver sample:" -ForegroundColor White
Write-Host "    . '$EnvFile'"
Write-Host "    & '$C2dSampleExe'"

Write-Host ""
