#!/usr/bin/env python3
# Copyright (c) Microsoft. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.

"""Generate tests/support/su_root_key_package_vectors.h from a Microsoft root key package.

The output is committed; tests never run this. It holds the package's signed bytes (the
`protected` object, serialized compactly as the Device Update agent does) and one RS256
signature per root, so the compiled-in roots are checked against the published package.

    python3 c/tests/support/gen_su_root_key_package_vectors.py rootkeypackage-<v>.json \
        > c/tests/support/su_root_key_package_vectors.h
"""

import base64
import json
import sys


def b64url(s):
    return base64.urlsafe_b64decode(s + "=" * (-len(s) % 4))


def emit_bytes(name, data):
    print(f"static const uint8_t {name}[] = {{")
    for i in range(0, len(data), 16):
        print("  " + ", ".join(f"0x{b:02x}" for b in data[i : i + 16]) + ",")
    print("};\n")


def main():
    with open(sys.argv[1], "rb") as f:
        package = json.loads(f.read())
    protected = package["protected"]
    signed = json.dumps(protected, separators=(",", ":")).replace("/", "\\/").encode()
    kids = list(protected["rootKeys"])
    if len(package["signatures"]) != len(kids):
        sys.exit("signature count does not match root count")

    print(
        """// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license
// information.

/* SPDX-License-Identifier: MIT */
/**
 * @file su_root_key_package_vectors.h
 * @brief Microsoft production root key package known answers. GENERATED by
 * gen_su_root_key_package_vectors.py; do not edit.
 */
#ifndef SU_ROOT_KEY_PACKAGE_VECTORS_H
#define SU_ROOT_KEY_PACKAGE_VECTORS_H

#include <stddef.h>
#include <stdint.h>

/* clang-format off */
"""
    )
    print(f"/** @brief Root key package version. */\n#define SU_ROOT_KEY_PACKAGE_VERSION {protected['version']}\n")
    print("/** @brief Signed bytes: the package's `protected` object. */")
    emit_bytes("k_su_root_key_package_signed", signed)
    for i, kid in enumerate(kids):
        sig = package["signatures"][i]
        if sig["alg"] != "RS256":
            sys.exit(f"unexpected alg for {kid}")
        emit_bytes(f"k_su_root_key_package_sig_{i}", b64url(sig["sig"]))

    print("/** @brief One root's RS256 signature over k_su_root_key_package_signed. */")
    print("typedef struct su_root_key_package_signature\n{")
    print("  const char* kid;\n  const uint8_t* signature;\n  size_t signature_len;")
    print("} su_root_key_package_signature;\n")
    print("static const su_root_key_package_signature k_su_root_key_package_signatures[] = {")
    for i, kid in enumerate(kids):
        print(f'  {{ "{kid}", k_su_root_key_package_sig_{i}, sizeof(k_su_root_key_package_sig_{i}) }},')
    print("};\n")
    print("/* clang-format on */\n\n#endif /* SU_ROOT_KEY_PACKAGE_VECTORS_H */")


if __name__ == "__main__":
    main()
