name: cd-dotnet # This only publishes to a private nuget feed attached to this github repo

on:
  workflow_dispatch:
  schedule:
  - cron: '0 11 * * *'  # Nightly at 4am PST


# only allow one run / branch at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  packages: write
    
jobs:
  build:
    runs-on: ubuntu-latest
    name: cd-dotnet
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v6

    - run: |
        dotnet nuget add source --username timtay-microsoft --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name azure-iot-sdk "https://nuget.pkg.github.com/Azure/index.json"
        dotnet nuget list source

        date="$(date +%F)"
        versionWithSuffix="1.0.0-"$date

        dotnet pack ./dotnet/src/Microsoft.Azure.Devices.Client/Microsoft.Azure.Devices.Client.csproj /p:Version=$versionWithSuffix
        dotnet nuget push "./dotnet/src/Microsoft.Azure.Devices.Client/bin/Release/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/Azure

